package transferFiles.model.IdUtil;


import javax.persistence.*;
import java.io.Serializable;

// extend class => get autogenerated ID
@MappedSuperclass
public class IdAutoGenerator implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column
    private int Id;

    public IdAutoGenerator() {
    }

    public int getId() {
        return Id;
    }

    public void setId(int id) {
        Id = id;
    }

    @Override
    public String toString() {
        return "Id=" + Id;
    }
}
